export default {
    //登录ACTION
    LOGIN_START:'LOGIN_START',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGIN_ERROR:'LOGIN_ERROR',

    //获取位置
    GET_LOCATION:'GET_LOCATION',
    GET_LOCATION_ERROR:'GET_LOCATION_ERROR',

    //获取城市列表
    GET_CITY_LIST:'GET_CITY_LIST',
    GET_CITY_LIST_ERROR:'GET_CITY_LIST_ERROR',

    //设置城市
    SET_CITY:'SET_CITY',

    //进入主页时是否定位，提高逼格，无实际作用
    CHANGE_LOCATION_STATE:'CHANGE_LOCATION_STATE'
}